### PR TITLE
Omnibus

### PR DESCRIPTION
**Pull request by faddat**
This PR:

* ensure there aren't version conflicts
* ensure that alliance doesn't cause unpatched chains to have issues with the dragon
* bump cosmos-sdk to v0.46.8
* bump ibc-go to v6.1.0
* remove all pieces of ignite so we don't depend on that import
  * cosmoscmd
  * openapiconsole 
* added a real cmd folder

Description:

This is an omnibus PR (not tightly scoped) aimed at making the repository easier to use over time.  Future PR's can be tightly scoped, but this one involved upgrading multiple connected software components.

### CODE REVIEW

**Comment by javiersuweijie** [comment]
Thanks for the PR @faddat 
Before merging, we just want to make sure our development workflow is still working. We also need to update Makefile to include everything that we need migrating from ignite cli
1. Generate go from protobufs
2. Docs and swagger (Think you fixed this, will need to verify)
3. Helpers to run a single node localnet

**Comment by javiersuweijie** [comment]
- [x] Generate go from protobufs - `make proto-gen`
- [x] Docs and swagger
- [x] Helpers to run a single node localnet - `make serve`

**Review by javiersuweijie — APPROVED** [review]

**Comment by emidev98** [comment]
Good PR! Some improvements here:
- [X] make localnet commands work,
- [X] delete unnecessary ignite files.

We may also need a command to build the ts-client from the proto files.

**Comment by faddat** [comment]
ah, so, interestingly, ignite cli will still work.  You can still use the same dev workflow. 

The key to this PR is that it removes the imports for ignite, but allows you to use the tooling :)

**Comment by javiersuweijie** [comment]
@faddat 

Running with ignite v0.26.1 and `ignite g proto-go` on the main branch has some weird behavior that downgrades the cosmos-sdk version. It also updates a bunch of other deps in my `go.mod`.

**Comment by faddat** [comment]
indeed!

Same here.  I think I may have patched it.

https://github.com/ignite/cli/pull/3426

not sure yet

**Comment by faddat** [comment]
update: that didn't work

**Pull request merged**
