### PR TITLE
fix: annotate the proper amino names on the proto messages

### PR DESCRIPTION
**Pull request by madrezaz**
Currently, generated clients use default message name as the message's amino name as there is no `amino.name` annotation on the proto messages. This PR intends to add the amino names registered on amino codecs to the proto.

### CODE REVIEW

**Comment by emidev98** [comment]
Thanks for the PR @madrezaz, very well seen! Will it be relevant to add the amino names for the governance proposals? 
image

**Comment by madrezaz** [comment]
@emidev98 Well I'm not sure about this as these are legacy proposals, but considering [cosmos-sdk as example](https://github.com/cosmos/gaia/blob/main/third_party/proto/cosmos/upgrade/v1beta1/upgrade.proto#L47), I think it's not needed.

**Review by emidev98 — APPROVED** [review]
Perfect! Thanks for the PR, I'll be waiting for @javiersuweijie review and we'll be good to merge and release a new version

**Review by javiersuweijie — APPROVED** [review]
LGTM. thanks

**Pull request merged**
